version: '3.7'

services:
    es1:
        image: elasticsearch:7.9.0
        container_name: es1-7-9-0
        restart: always
        environment:
            - TZ=Asia/Shanghai
            - node.name=es1-7-9-0
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es2-7-9-0
            - cluster.initial_master_nodes=es1-7-9-0,es2-7-9-0
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./es1/data:/usr/share/elasticsearch/data
            - ./es1/logs:/usr/share/elasticsearch/logs
            - ./es1/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - ./es1/plugins/:/usr/share/elasticsearch/plugins/
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - esnet

    es2:
        image: elasticsearch:7.9.0
        container_name: es2-7-9-0
        restart: always
        environment:
            - TZ=Asia/Shanghai
            - node.name=es2-7-9-0
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es1-7-9-0
            - cluster.initial_master_nodes=es1-7-9-0,es2-7-9-0
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./es2/data:/usr/share/elasticsearch/data
            - ./es2/logs:/usr/share/elasticsearch/logs
            - ./es2/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - ./es2/plugins/:/usr/share/elasticsearch/plugins/
        networks:
            - esnet

    kibana:
        image: kibana:7.9.0
        restart: always
        container_name: kibana-7-9-0
        ports:
            - 5601:5601
        volumes:
            - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
        environment:
            - TZ=Asia/Shanghai
        logging:
            driver: 'json-file'
            options:
                max-size: '30m'
                max-file: '1'

    logstash:
        image: logstash:7.9.0
        restart: always
        container_name: logstash-7-9-0
        ports:
            - 5601:5601
        volumes:
            - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
        environment:
            - TZ=Asia/Shanghai
        logging:
            driver: 'json-file'
            options:
                max-size: '30m'
                max-file: '1'

networks:
  esnet: