version: "3.8"

services:
    nginx:
        # 依赖的容器 容器名:版本号
        image: openzipkin/zipkin
        # 镜像名 不能与其他镜像名重复
        container_name: zipkin
        # 是否自启动
        restart: always
        # 时区
        environment:
            - TZ=Asia/Shanghai
        # 映射端口 容器端口不需要更改 宿主机端口:容器端口
        ports:
            - 9411:9411