version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:7.8.0
    container_name: es1
    environment:
      - node.name=master
      - cluster.name=elasticsearch_cluster1
      - cluster.initial_master_nodes=es1,es2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es1/data:/usr/share/elasticsearch/data
      - ./es1/logs:/usr/share/elasticsearch/logs
    ports:
      - 19200:9200
      - 19300:9300
    networks:
      - esnet
  elasticsearch2:
    image: elasticsearch:7.8.0
    container_name: es2
    environment:
      - node.name=master
      - cluster.name=elasticsearch_cluster2
      - cluster.initial_master_nodes=es1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es2/data:/usr/share/elasticsearch/data
      - ./es2/logs:/usr/share/elasticsearch/logs
    networks:
      - esnet

networks:
  esnet: