version: '3.7'

services:
    postgresql:
        image: postgres:9.6
        restart: always
        expose:
            - '5432:5432'
        environment:
            - POSTGRES_USER=example
            - POSTGRES_PASSWORD=example
            - POSTGRES_DB=my_db
            # 账号
            - POSTGRES_USER=postgres
            # 密码
            - POSTGRES_PASS=111111
        volumes:
            - ./data/:/var/lib/postgresql
        logging:
            driver: 'json-file'
            options:
                max-size: '30m'
                max-file: '1'
