version: '3.7'

services:
    postgresql:
        image: postgres:9.6
        restart: always
        container_name: pgsql
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_PASS=111111
        volumes:
            - ./data/:/var/lib/postgresql
        logging:
            driver: 'json-file'
            options:
                max-size: '30m'
                max-file: '1'
