version: "3.7"

services:
    openjdk8:
        build: .
        image: teler/openjdk-alpine:1.8-0.0.1
        restart: always
        environment:
            TZ: 'Asia/Shanghai'
        logging:
            driver: 'json-file'
            options:
                max-size: '30m'
                max-file: '1'
