version: '3.7'

services:
    postgresql:
        image: postgis/postgis:9.6-2.5
        restart: always
        container_name: pgsql
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_PASSWORD=123456
            - ALLOW_IP_RANGE=0.0.0.0/0 
        volumes:
            #如果不到/var/lib/postgresql/data 数据可能挂载不出来
            - ./data/:/var/lib/postgresql/data
        logging:
            driver: 'json-file'
            options:
                max-size: '30m'
                max-file: '1'
