version: '3.7'

services:
    mongodb:
        image: mongo
        restart: always
        container_name: "mongo"
        ports:
            - "27017:27017"
        environment:
            # 如果不想链接时有密码 可以删掉
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=111111
        volumes:
            - ./data/db/:/data/db
            - ./conf:/data/configdb
        logging:
            driver: 'json-file'
            options:
                max-size: '30m'
                max-file: '1'