version: '3.7'

services:
    mongodb:
        image: mongo
        restart: always
        container_name: "mongo"
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=111111
        volumes:
            - ./data/db/:/var/lib/postgresql
        logging:
            driver: 'json-file'
            options:
                max-size: '30m'
                max-file: '1'