version: '3.8'

services:
  namesrv:
    image: apache/rocketmq:5.1.4
    container_name: rocketmq-namesrv
    ports:
      - 9876:9876
    volumes:
      - ./namesrv/logs:/usr/local/rocketmq/data/namesrv/logs
      - ./namesrv/store:/usr/local/rocketmq/data/namesrv/store
    command: sh mqnamesrv

  broker:
    image: apache/rocketmq:5.1.4
    container_name: rocketmq-broker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - ./broker/logs:/home/rocketmq/logs
      - ./broker/store:/home/rocketmq/store
      - ./broker/conf/broker.conf:/home/rocketmq/rocketmq/conf/broker.conf
    command: sh mqbroker -c /home/rocketmq/rocketmq/conf/broker.conf -n namesrv:9876
    depends_on:
      - namesrv

  rmqconsole:
    image: apacherocketmq/rocketmq-console:2.0.0
    container_name: rocketmq-console
    ports:
      - 9877:8080
    environment:
      - JAVA_OPTS= -Dlogging.level.root=info  -Drocketmq.namesrv.addr=namesrv:9876
      - Dcom.rocketmq.sendMessageWithVIPChannel=false
    depends_on:
      - namesrv