version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:5.4.2
    container_name: es1-5-4-2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es1/data:/usr/share/elasticsearch/data
      - ./es1/logs:/usr/share/elasticsearch/logs
      - ./es1/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 19200:9200
      - 19300:9300
    networks:
      - esnet
  elasticsearch2:
    image: elasticsearch:5.4.2
    container_name: es2-5-4-2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es2/data:/usr/share/elasticsearch/data
      - ./es2/logs:/usr/share/elasticsearch/logs
      - ./es2/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - esnet
  elasticsearch-head:
    image: mobz/elasticsearch-head:5-alpine
    container_name: es-head
    ports:
      - 19201:9100


networks:
  esnet: