version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:5.4.2
    container_name: es1-5-4-2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es1/data:/usr/share/elasticsearch/data
      - ./es1/logs:/usr/share/elasticsearch/logs
    ports:
      - 15108:9200
      - 15109:9300
    networks:
      - esnet
  elasticsearch2:
    image: elasticsearch:5.4.2
    container_name: es2-5-4-2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=es1-5-4-2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es2/data:/usr/share/elasticsearch/data
      - ./es2/logs:/usr/share/elasticsearch/logs
    networks:
      - esnet

networks:
  esnet: