version: "3.7"

services:
    consul:
        image: consul:1.8.5
        container_name: consul
        restart: always
        environment:
            TZ: 'Asia/Shanghai'
        ports:
            - 8500:8500
        logging:
            driver: 'json-file'
            options:
                max-size: '30m'
                max-file: '1'
