version: "3.8"

services:
    nginx:
        # 依赖的容器 容器名:版本号
        image: nginx:latest
        # 镜像名 不能与其他镜像名重复
        container_name: nginx
        # 是否自启动
        restart: always
        # 时区
        environment:
            - TZ=Asia/Shanghai
        # 映射端口 容器端口不需要更改 宿主机端口:容器端口
        ports:
            - 80:80
        # 绑定
        volumes:
            - ./conf/nginx.conf:/etc/nginx/nginx.conf
            - ./conf.d:/etc/nginx/conf.d
            - ./log:/var/log/nginx
            - ./html:/usr/share/nginx/html