version: '3.7'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-namenode
    volumes:
      - ./data/namenode:/hadoop/dfs/name
      - ./config/hdfs-site.xml:/opt/hadoop-3.2.1/etc/hadoop/hdfs-site.xml
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./config/hadoop.env
    ports:
      - 50070:50070
      - 9870:9870

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    depends_on:
      - namenode
    volumes:
      - ./data/datanode:/hadoop/dfs/data
    env_file:
      - ./config/hadoop.env
    ports:
      - 50075:50075

  spark-master:
    image: bde2020/spark-master:3.0.0-hadoop3.2
    container_name: spark-master
    ports:
      - 6066:6066
      - 8080:8080
      - 7077:7077
    env_file:
      - ./config/hadoop.env

  spark-worker:
    image: bde2020/spark-master:3.0.0-hadoop3.2
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - 8081:8081
    env_file:
      - ./config/hadoop.env

  spark-notebook:
    image: bde2020/spark-master:3.0.0-hadoop3.2
    container_name: spark-notebook
    env_file:
      - ./config/hadoop.env
    ports:
      - 9001:9001

  hue:
    image: bde2020/hdfs-filebrowser:3.11
    ports:
      - 8088:8088
    environment:
      - NAMENODE_HOST=namenode
