version: "3.8"

services:
    portainer:
        image: portainer/portainer:1.24.1-alpine
        container_name: portainer
        restart: always
        environment:
            TZ: 'Asia/Shanghai'
        ports:
            - 9000:9000
            - 8000:8000
        volumes:
            - ./data/:/data
            - /var/run/docker.sock:/var/run/docker.sock
        logging:
            driver: 'json-file'
            options:
                max-size: '30m'
                max-file: '1'
