version: "3.8"

services:
    mysql:
        image: mysql:latest
        restart: always
        container_name: mysql
        ports:
            - 3306:3306
        environment:
            - TZ=Asia/Shanghai
            # 密码
            - MYSQL_ROOT_PASSWORD=111111
            - character-set-client-handshake=FALSE
            - character-set-server=utf8mb4
            - collation-server=utf8mb4_unicode_ci
            - explicit_defaults_for_timestamp=true
            - max_allowed_packet=10M
        volumes:
            - ./data/:/var/lib/mysql
            - ./conf:/etc/mysql/mysql.conf.d
            - ./logs:/var/log/mysql
        # 最大连接数
        command: ["--max_connections=300","lower_case_table_names=1"]
        logging:
            driver: 'json-file'
            options:
                max-size: '30m'
                max-file: '1'

