version: "3.8"

services:
    openjdk11:
        build: .
        image: teler/openjdk-alpine:11-0.0.1
        container_name: openjdk11-alpine
        restart: always
        environment:
            TZ: 'Asia/Shanghai'
        logging:
            driver: 'json-file'
            options:
                max-size: '30m'
                max-file: '1'
