version: '3'

services:
    redis:
        image: redis
        container_name: "redis"
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - ./data/:/data
            - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
        logging:
            driver: 'json-file'
            options:
                max-size: '30m'
                max-file: '1'
