version: "3.8"

services:
    redis:
        image: redis:6.2
        container_name: redis
        restart: always
        environment:
            TZ: 'Asia/Shanghai'
        command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--appendonly", "yes"]
        ports:
            - 6379:6379
        volumes:
            - ./data/:/data
            - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
        logging:
            driver: 'json-file'
            options:
                max-size: '30m'
                max-file: '1'
